[build]
  base = "vite-project/"
  publish = "vite-project/dist/"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://your-backend-url.herokuapp.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_ENVIRONMENT = "production" }

[context.preview]
  environment = { VITE_ENVIRONMENT = "preview" }

[context.branch-deploy]
  environment = { VITE_ENVIRONMENT = "development" }
